### ISSUE TITLE
Add Google Maps / Waze links for the Address field

### ISSUE THREAD

**Issue by ag-ayush** [ag-ayush/rideboard#13]
It would be nice if you could click the address, or an icon near the address that would open up maps application and search the address.

**Comment by mxmeinhold** [comment]
The Google Maps API supports cross platform links, allowing [searching](https://developers.google.com/maps/documentation/urls/guide#search-action) for an address. This url will either open in a web browser or, for mobile devices with maps installed, will open in the google maps app, allowing users to quickly get directions from their current location.

**Comment by ag-ayush** [comment]
#14 Adds this feature, should consider making it a clickable icon such as https://fontawesome.com/icons/map-marker-alt?style=solid in future, closing for now.
